<?php
namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class SeederCountriesStatesCities2 extends Seeder
{
    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        // check if table vpr_countries_states_cities is empty
        DB::table('vpr_countries_states_cities')->insert([
            ['id_city' => 909, 'id_state' => 5, 'name' => 'Itacaré'],
            ['id_city' => 910, 'id_state' => 5, 'name' => 'Itacava'],
            ['id_city' => 911, 'id_state' => 5, 'name' => 'Itachama'],
            ['id_city' => 912, 'id_state' => 5, 'name' => 'Itacimirim'],
            ['id_city' => 913, 'id_state' => 5, 'name' => 'Itaeté'],
            ['id_city' => 914, 'id_state' => 5, 'name' => 'Itagi'],
            ['id_city' => 915, 'id_state' => 5, 'name' => 'Itagibá'],
            ['id_city' => 916, 'id_state' => 5, 'name' => 'Itagimirim'],
            ['id_city' => 917, 'id_state' => 5, 'name' => 'Itaguaçu da Bahia'],
            ['id_city' => 918, 'id_state' => 5, 'name' => 'Itaia'],
            ['id_city' => 919, 'id_state' => 5, 'name' => 'Itaibó'],
            ['id_city' => 920, 'id_state' => 5, 'name' => 'Itaipu'],
            ['id_city' => 921, 'id_state' => 5, 'name' => 'Itaítu'],
            ['id_city' => 922, 'id_state' => 5, 'name' => 'Itajaí'],
            ['id_city' => 923, 'id_state' => 5, 'name' => 'Itaju do Colônia'],
            ['id_city' => 924, 'id_state' => 5, 'name' => 'Itajubaquara'],
            ['id_city' => 925, 'id_state' => 5, 'name' => 'Itajuípe'],
            ['id_city' => 926, 'id_state' => 5, 'name' => 'Itajuru'],
            ['id_city' => 927, 'id_state' => 5, 'name' => 'Itamaraju'],
            ['id_city' => 928, 'id_state' => 5, 'name' => 'Itamari'],
            ['id_city' => 929, 'id_state' => 5, 'name' => 'Itambé'],
            ['id_city' => 930, 'id_state' => 5, 'name' => 'Itamira'],
            ['id_city' => 931, 'id_state' => 5, 'name' => 'Itamotinga'],
            ['id_city' => 932, 'id_state' => 5, 'name' => 'Itanagé'],
            ['id_city' => 933, 'id_state' => 5, 'name' => 'Itanagra'],
            ['id_city' => 934, 'id_state' => 5, 'name' => 'Itanhém'],
            ['id_city' => 935, 'id_state' => 5, 'name' => 'Itanhi'],
            ['id_city' => 936, 'id_state' => 5, 'name' => 'Itaparica'],
            ['id_city' => 937, 'id_state' => 5, 'name' => 'Itapé'],
            ['id_city' => 938, 'id_state' => 5, 'name' => 'Itapebi'],
            ['id_city' => 939, 'id_state' => 5, 'name' => 'Itapeipu'],
            ['id_city' => 940, 'id_state' => 5, 'name' => 'Itapetinga'],
            ['id_city' => 941, 'id_state' => 5, 'name' => 'Itapicuru'],
            ['id_city' => 942, 'id_state' => 5, 'name' => 'Itapirema'],
            ['id_city' => 943, 'id_state' => 5, 'name' => 'Itapitanga'],
            ['id_city' => 944, 'id_state' => 5, 'name' => 'Itapora'],
            ['id_city' => 945, 'id_state' => 5, 'name' => 'Itaquara'],
            ['id_city' => 946, 'id_state' => 5, 'name' => 'Itaquaraí'],
            ['id_city' => 947, 'id_state' => 5, 'name' => 'Itarantim'],
            ['id_city' => 948, 'id_state' => 5, 'name' => 'Itati'],
            ['id_city' => 949, 'id_state' => 5, 'name' => 'Itatim'],
            ['id_city' => 950, 'id_state' => 5, 'name' => 'Itatingui'],
            ['id_city' => 951, 'id_state' => 5, 'name' => 'Itiruçu'],
            ['id_city' => 952, 'id_state' => 5, 'name' => 'Itiúba'],
            ['id_city' => 953, 'id_state' => 5, 'name' => 'Itororó'],
            ['id_city' => 954, 'id_state' => 5, 'name' => 'Ituaçu'],
            ['id_city' => 955, 'id_state' => 5, 'name' => 'Ituberá'],
            ['id_city' => 956, 'id_state' => 5, 'name' => 'Itupeva'],
            ['id_city' => 957, 'id_state' => 5, 'name' => 'Iuiu'],
            ['id_city' => 958, 'id_state' => 5, 'name' => 'Jaborandi'],
            ['id_city' => 959, 'id_state' => 5, 'name' => 'Jacaraci'],
            ['id_city' => 960, 'id_state' => 5, 'name' => 'Jacobina'],
            ['id_city' => 961, 'id_state' => 5, 'name' => 'Jacu'],
            ['id_city' => 962, 'id_state' => 5, 'name' => 'Jacuípe'],
            ['id_city' => 963, 'id_state' => 5, 'name' => 'Jacuruna'],
            ['id_city' => 964, 'id_state' => 5, 'name' => 'Jaguaquara'],
            ['id_city' => 965, 'id_state' => 5, 'name' => 'Jaguara'],
            ['id_city' => 966, 'id_state' => 5, 'name' => 'Jaguarari'],
            ['id_city' => 967, 'id_state' => 5, 'name' => 'Jaguaripe'],
            ['id_city' => 968, 'id_state' => 5, 'name' => 'Jaíba'],
            ['id_city' => 969, 'id_state' => 5, 'name' => 'Jandaíra'],
            ['id_city' => 970, 'id_state' => 5, 'name' => 'Japomirim'],
            ['id_city' => 971, 'id_state' => 5, 'name' => 'Japu'],
            ['id_city' => 972, 'id_state' => 5, 'name' => 'Jauá'],
            ['id_city' => 973, 'id_state' => 5, 'name' => 'Jequié'],
            ['id_city' => 974, 'id_state' => 5, 'name' => 'Jequiriçá'],
            ['id_city' => 975, 'id_state' => 5, 'name' => 'Jeremoabo'],
            ['id_city' => 976, 'id_state' => 5, 'name' => 'Jiribatuba'],
            ['id_city' => 977, 'id_state' => 5, 'name' => 'Jitaúna'],
            ['id_city' => 978, 'id_state' => 5, 'name' => 'João Amaro'],
            ['id_city' => 979, 'id_state' => 5, 'name' => 'João Correia'],
            ['id_city' => 980, 'id_state' => 5, 'name' => 'João Dourado'],
            ['id_city' => 981, 'id_state' => 5, 'name' => 'José Gonçalves'],
            ['id_city' => 982, 'id_state' => 5, 'name' => 'Juacema'],
            ['id_city' => 983, 'id_state' => 5, 'name' => 'Juazeiro'],
            ['id_city' => 984, 'id_state' => 5, 'name' => 'Jucuruçu'],
            ['id_city' => 985, 'id_state' => 5, 'name' => 'Juerana'],
            ['id_city' => 986, 'id_state' => 5, 'name' => 'Junco'],
            ['id_city' => 987, 'id_state' => 5, 'name' => 'Jupaguá'],
            ['id_city' => 988, 'id_state' => 5, 'name' => 'Juraci'],
            ['id_city' => 989, 'id_state' => 5, 'name' => 'Juremal'],
            ['id_city' => 990, 'id_state' => 5, 'name' => 'Jussara'],
            ['id_city' => 991, 'id_state' => 5, 'name' => 'Jussari'],
            ['id_city' => 992, 'id_state' => 5, 'name' => 'Jussiape'],
            ['id_city' => 993, 'id_state' => 5, 'name' => 'Km Sete'],
            ['id_city' => 994, 'id_state' => 5, 'name' => 'Lafaiete Coutinho'],
            ['id_city' => 995, 'id_state' => 5, 'name' => 'Lagoa Clara'],
            ['id_city' => 996, 'id_state' => 5, 'name' => 'Lagoa de Melquíades'],
            ['id_city' => 997, 'id_state' => 5, 'name' => 'Lagoa do Boi'],
            ['id_city' => 998, 'id_state' => 5, 'name' => 'Lagoa Grande'],
            ['id_city' => 999, 'id_state' => 5, 'name' => 'Lagoa José Luís'],
            ['id_city' => 1000, 'id_state' => 5, 'name' => 'Lagoa Preta'],
            ['id_city' => 1001, 'id_state' => 5, 'name' => 'Lagoa Real'],
            ['id_city' => 1002, 'id_state' => 5, 'name' => 'Laje'],
            ['id_city' => 1003, 'id_state' => 5, 'name' => 'Laje do Banco'],
            ['id_city' => 1004, 'id_state' => 5, 'name' => 'Lajedão'],
            ['id_city' => 1005, 'id_state' => 5, 'name' => 'Lajedinho'],
            ['id_city' => 1006, 'id_state' => 5, 'name' => 'Lajedo Alto'],
            ['id_city' => 1007, 'id_state' => 5, 'name' => 'Lajedo do Tabocal'],
            ['id_city' => 1008, 'id_state' => 5, 'name' => 'Lamarão'],
            ['id_city' => 1009, 'id_state' => 5, 'name' => 'Lamarão do Passe'],
            ['id_city' => 1010, 'id_state' => 5, 'name' => 'Lapão'],
            ['id_city' => 1011, 'id_state' => 5, 'name' => 'Largo'],
            ['id_city' => 1012, 'id_state' => 5, 'name' => 'Lauro de Freitas'],
            ['id_city' => 1013, 'id_state' => 5, 'name' => 'Lençóis'],
            ['id_city' => 1014, 'id_state' => 5, 'name' => 'Licínio de Almeida'],
            ['id_city' => 1015, 'id_state' => 5, 'name' => 'Limoeiro do Bom Viver'],
            ['id_city' => 1016, 'id_state' => 5, 'name' => 'Livramento de Nossa Senhora'],
            ['id_city' => 1017, 'id_state' => 5, 'name' => 'Lucaia'],
            ['id_city' => 1018, 'id_state' => 5, 'name' => 'Luís Viana'],
            ['id_city' => 1019, 'id_state' => 5, 'name' => 'Lustosa'],
            ['id_city' => 1020, 'id_state' => 5, 'name' => 'Macajuba'],
            ['id_city' => 1021, 'id_state' => 5, 'name' => 'Macarani'],
            ['id_city' => 1022, 'id_state' => 5, 'name' => 'Macaúbas'],
            ['id_city' => 1023, 'id_state' => 5, 'name' => 'Macururé'],
            ['id_city' => 1024, 'id_state' => 5, 'name' => 'Madre de Deus'],
            ['id_city' => 1025, 'id_state' => 5, 'name' => 'Maetinga'],
            ['id_city' => 1026, 'id_state' => 5, 'name' => 'Maiquinique'],
            ['id_city' => 1027, 'id_state' => 5, 'name' => 'Mairi'],
            ['id_city' => 1028, 'id_state' => 5, 'name' => 'Malhada'],
            ['id_city' => 1029, 'id_state' => 5, 'name' => 'Malhada de Pedras'],
            ['id_city' => 1030, 'id_state' => 5, 'name' => 'Mandiroba'],
            ['id_city' => 1031, 'id_state' => 5, 'name' => 'Mangue Seco'],
            ['id_city' => 1032, 'id_state' => 5, 'name' => 'Maniaçu'],
            ['id_city' => 1033, 'id_state' => 5, 'name' => 'Manoel Vitorino'],
            ['id_city' => 1034, 'id_state' => 5, 'name' => 'Mansidão'],
            ['id_city' => 1035, 'id_state' => 5, 'name' => 'Mantiba'],
            ['id_city' => 1036, 'id_state' => 5, 'name' => 'Mar Grande'],
            ['id_city' => 1037, 'id_state' => 5, 'name' => 'Maracás'],
            ['id_city' => 1038, 'id_state' => 5, 'name' => 'Maragogipe'],
            ['id_city' => 1039, 'id_state' => 5, 'name' => 'Maragogipinho'],
            ['id_city' => 1040, 'id_state' => 5, 'name' => 'Maraú'],
            ['id_city' => 1041, 'id_state' => 5, 'name' => 'Marcionílio Souza'],
            ['id_city' => 1042, 'id_state' => 5, 'name' => 'Marcolino Moura'],
            ['id_city' => 1043, 'id_state' => 5, 'name' => 'Maria Quitéria'],
            ['id_city' => 1044, 'id_state' => 5, 'name' => 'Maricoabo'],
            ['id_city' => 1045, 'id_state' => 5, 'name' => 'Mariquita'],
            ['id_city' => 1046, 'id_state' => 5, 'name' => 'Mascote'],
            ['id_city' => 1047, 'id_state' => 5, 'name' => 'Massacara'],
            ['id_city' => 1048, 'id_state' => 5, 'name' => 'Massaroca'],
            ['id_city' => 1049, 'id_state' => 5, 'name' => 'Mata da Aliança'],
            ['id_city' => 1050, 'id_state' => 5, 'name' => 'Mata de São João'],
            ['id_city' => 1051, 'id_state' => 5, 'name' => 'Mataripe'],
            ['id_city' => 1052, 'id_state' => 5, 'name' => 'Matina'],
            ['id_city' => 1053, 'id_state' => 5, 'name' => 'Matinha'],
            ['id_city' => 1054, 'id_state' => 5, 'name' => 'Medeiros Neto'],
            ['id_city' => 1055, 'id_state' => 5, 'name' => 'Miguel Calmon'],
            ['id_city' => 1056, 'id_state' => 5, 'name' => 'Milagres'],
            ['id_city' => 1057, 'id_state' => 5, 'name' => 'Luís Eduardo Magalhães'],
            ['id_city' => 1058, 'id_state' => 5, 'name' => 'Minas do Espírito Santo'],
            ['id_city' => 1059, 'id_state' => 5, 'name' => 'Minas do Mimoso'],
            ['id_city' => 1060, 'id_state' => 5, 'name' => 'Mirandela'],
            ['id_city' => 1061, 'id_state' => 5, 'name' => 'Miranga'],
            ['id_city' => 1062, 'id_state' => 5, 'name' => 'Mirangaba'],
            ['id_city' => 1063, 'id_state' => 5, 'name' => 'Mirante'],
            ['id_city' => 1064, 'id_state' => 5, 'name' => 'Mocambo'],
            ['id_city' => 1065, 'id_state' => 5, 'name' => 'Mogiquiçaba'],
            ['id_city' => 1066, 'id_state' => 5, 'name' => 'Monte Cruzeiro'],
            ['id_city' => 1067, 'id_state' => 5, 'name' => 'Monte Gordo'],
            ['id_city' => 1068, 'id_state' => 5, 'name' => 'Monte Recôncavo'],
            ['id_city' => 1069, 'id_state' => 5, 'name' => 'Monte Santo'],
            ['id_city' => 1070, 'id_state' => 5, 'name' => 'Morpará'],
            ['id_city' => 1071, 'id_state' => 5, 'name' => 'Morrinhos'],
            ['id_city' => 1072, 'id_state' => 5, 'name' => 'Morro das Flores'],
            ['id_city' => 1073, 'id_state' => 5, 'name' => 'Morro de São Paulo'],
            ['id_city' => 1074, 'id_state' => 5, 'name' => 'Morro do Chapéu'],
            ['id_city' => 1075, 'id_state' => 5, 'name' => 'Mortugaba'],
            ['id_city' => 1076, 'id_state' => 5, 'name' => 'Mucugê'],
            ['id_city' => 1077, 'id_state' => 5, 'name' => 'Mucuri'],
            ['id_city' => 1078, 'id_state' => 5, 'name' => 'Mulungu do Morro'],
            ['id_city' => 1079, 'id_state' => 5, 'name' => 'Mundo Novo'],
            ['id_city' => 1080, 'id_state' => 5, 'name' => 'Muniz Ferreira'],
            ['id_city' => 1081, 'id_state' => 5, 'name' => 'Muquém de São Francisco'],
            ['id_city' => 1082, 'id_state' => 5, 'name' => 'Muritiba'],
            ['id_city' => 1083, 'id_state' => 5, 'name' => 'Mutas'],
            ['id_city' => 1084, 'id_state' => 5, 'name' => 'Mutuípe'],
            ['id_city' => 1085, 'id_state' => 5, 'name' => 'Nagé'],
            ['id_city' => 1086, 'id_state' => 5, 'name' => 'Narandiba'],
            ['id_city' => 1087, 'id_state' => 5, 'name' => 'Nazaré'],
            ['id_city' => 1088, 'id_state' => 5, 'name' => 'Nilo Peçanha'],
            ['id_city' => 1089, 'id_state' => 5, 'name' => 'Nordestina'],
            ['id_city' => 1090, 'id_state' => 5, 'name' => 'Nova Alegria'],
            ['id_city' => 1091, 'id_state' => 5, 'name' => 'Nova Brasília'],
            ['id_city' => 1092, 'id_state' => 5, 'name' => 'Nova Canaã'],
            ['id_city' => 1093, 'id_state' => 5, 'name' => 'Nova Fátima'],
            ['id_city' => 1094, 'id_state' => 5, 'name' => 'Nova Ibiá'],
            ['id_city' => 1095, 'id_state' => 5, 'name' => 'Nova Itaipê'],
            ['id_city' => 1096, 'id_state' => 5, 'name' => 'Nova Itarana'],
            ['id_city' => 1097, 'id_state' => 5, 'name' => 'Nova Lídice'],
            ['id_city' => 1098, 'id_state' => 5, 'name' => 'Nova Redenção'],
            ['id_city' => 1099, 'id_state' => 5, 'name' => 'Nova Soure'],
            ['id_city' => 1100, 'id_state' => 5, 'name' => 'Nova Viçosa'],
            ['id_city' => 1101, 'id_state' => 5, 'name' => 'Novo Acre'],
            ['id_city' => 1102, 'id_state' => 5, 'name' => 'Novo Horizonte'],
            ['id_city' => 1103, 'id_state' => 5, 'name' => 'Novo Triunfo'],
            ['id_city' => 1104, 'id_state' => 5, 'name' => 'Núcleo Residencial Pilar'],
            ['id_city' => 1105, 'id_state' => 5, 'name' => 'Nuguaçu'],
            ['id_city' => 1106, 'id_state' => 5, 'name' => 'Olhos D Água do Seco'],
            ['id_city' => 1107, 'id_state' => 5, 'name' => 'Olhos D Água do Serafim'],
            ['id_city' => 1108, 'id_state' => 5, 'name' => 'Olindina'],
            ['id_city' => 1109, 'id_state' => 5, 'name' => 'Oliveira dos Brejinhos'],
            ['id_city' => 1110, 'id_state' => 5, 'name' => 'Onha'],
            ['id_city' => 1111, 'id_state' => 5, 'name' => 'Oriente Novo'],
            ['id_city' => 1112, 'id_state' => 5, 'name' => 'Ouricana'],
            ['id_city' => 1113, 'id_state' => 5, 'name' => 'Ouriçangas'],
            ['id_city' => 1114, 'id_state' => 5, 'name' => 'Ouricuri do Ouro'],
            ['id_city' => 1115, 'id_state' => 5, 'name' => 'Ourolândia'],
            ['id_city' => 1116, 'id_state' => 5, 'name' => 'Outeiro Redondo'],
            ['id_city' => 1117, 'id_state' => 5, 'name' => 'Paiol'],
            ['id_city' => 1118, 'id_state' => 5, 'name' => 'Pajeú do Vento'],
            ['id_city' => 1119, 'id_state' => 5, 'name' => 'Palame'],
            ['id_city' => 1120, 'id_state' => 5, 'name' => 'Palmas de Monte Alto'],
            ['id_city' => 1121, 'id_state' => 5, 'name' => 'Palmeiras'],
            ['id_city' => 1122, 'id_state' => 5, 'name' => 'Parafuso'],
            ['id_city' => 1123, 'id_state' => 5, 'name' => 'Paramirim'],
            ['id_city' => 1124, 'id_state' => 5, 'name' => 'Parateca'],
            ['id_city' => 1125, 'id_state' => 5, 'name' => 'Paratinga'],
            ['id_city' => 1126, 'id_state' => 5, 'name' => 'Paripiranga'],
            ['id_city' => 1127, 'id_state' => 5, 'name' => 'Pataíba'],
            ['id_city' => 1128, 'id_state' => 5, 'name' => 'Patamuté'],
            ['id_city' => 1129, 'id_state' => 5, 'name' => 'Pau a Pique'],
            ['id_city' => 1130, 'id_state' => 5, 'name' => 'Pau Brasil'],
            ['id_city' => 1131, 'id_state' => 5, 'name' => 'Paulo Afonso'],
            ['id_city' => 1132, 'id_state' => 5, 'name' => 'Pé de Serra'],
            ['id_city' => 1133, 'id_state' => 5, 'name' => 'Pedrão'],
            ['id_city' => 1134, 'id_state' => 5, 'name' => 'Pedras Altas do Mirim'],
            ['id_city' => 1135, 'id_state' => 5, 'name' => 'Pedro Alexandre'],
            ['id_city' => 1136, 'id_state' => 5, 'name' => 'Peixe'],
            ['id_city' => 1137, 'id_state' => 5, 'name' => 'Petim'],
            ['id_city' => 1138, 'id_state' => 5, 'name' => 'Piabanha'],
            ['id_city' => 1139, 'id_state' => 5, 'name' => 'Piatã'],
            ['id_city' => 1140, 'id_state' => 5, 'name' => 'Piçarrão'],
            ['id_city' => 1141, 'id_state' => 5, 'name' => 'Pilão Arcado'],
            ['id_city' => 1142, 'id_state' => 5, 'name' => 'Pimenteira'],
            ['id_city' => 1143, 'id_state' => 5, 'name' => 'Pindaí'],
            ['id_city' => 1144, 'id_state' => 5, 'name' => 'Pindobaçu'],
            ['id_city' => 1145, 'id_state' => 5, 'name' => 'Pinhões'],
            ['id_city' => 1146, 'id_state' => 5, 'name' => 'Pintadas'],
            ['id_city' => 1147, 'id_state' => 5, 'name' => 'Piragi'],
            ['id_city' => 1148, 'id_state' => 5, 'name' => 'Piraí do Norte'],
            ['id_city' => 1149, 'id_state' => 5, 'name' => 'Pirajá'],
            ['id_city' => 1150, 'id_state' => 5, 'name' => 'Pirajuia'],
            ['id_city' => 1151, 'id_state' => 5, 'name' => 'Piri'],
            ['id_city' => 1152, 'id_state' => 5, 'name' => 'Piripá'],
            ['id_city' => 1153, 'id_state' => 5, 'name' => 'Piritiba'],
            ['id_city' => 1154, 'id_state' => 5, 'name' => 'Pituba'],
            ['id_city' => 1155, 'id_state' => 5, 'name' => 'Planaltino'],
            ['id_city' => 1156, 'id_state' => 5, 'name' => 'Planalto'],
            ['id_city' => 1157, 'id_state' => 5, 'name' => 'Poço Central'],
            ['id_city' => 1158, 'id_state' => 5, 'name' => 'Poço de Fora'],
            ['id_city' => 1159, 'id_state' => 5, 'name' => 'Poções'],
            ['id_city' => 1160, 'id_state' => 5, 'name' => 'Poços'],
            ['id_city' => 1161, 'id_state' => 5, 'name' => 'Pojuca'],
            ['id_city' => 1162, 'id_state' => 5, 'name' => 'Polo Petroquímico de Camaçari'],
            ['id_city' => 1163, 'id_state' => 5, 'name' => 'Ponta da Areia'],
            ['id_city' => 1164, 'id_state' => 5, 'name' => 'Ponto Novo'],
            ['id_city' => 1165, 'id_state' => 5, 'name' => 'Porto Novo'],
            ['id_city' => 1166, 'id_state' => 5, 'name' => 'Porto Seguro'],
            ['id_city' => 1167, 'id_state' => 5, 'name' => 'Posto da Mata'],
            ['id_city' => 1168, 'id_state' => 5, 'name' => 'Potiraguá'],
            ['id_city' => 1169, 'id_state' => 5, 'name' => 'Poxim do Sul'],
            ['id_city' => 1170, 'id_state' => 5, 'name' => 'Prado'],
            ['id_city' => 1171, 'id_state' => 5, 'name' => 'Presidente Dutra'],
            ['id_city' => 1172, 'id_state' => 5, 'name' => 'Presidente Jânio Quadros'],
            ['id_city' => 1173, 'id_state' => 5, 'name' => 'Presidente Tancredo Neves'],
            ['id_city' => 1174, 'id_state' => 5, 'name' => 'Prevenido'],
            ['id_city' => 1175, 'id_state' => 5, 'name' => 'Quaraçu'],
            ['id_city' => 1176, 'id_state' => 5, 'name' => 'Queimadas'],
            ['id_city' => 1177, 'id_state' => 5, 'name' => 'Quijingue'],
            ['id_city' => 1178, 'id_state' => 5, 'name' => 'Quixabá'],
            ['id_city' => 1179, 'id_state' => 5, 'name' => 'Quixabeira'],
            ['id_city' => 1180, 'id_state' => 5, 'name' => 'Rafael Jambeiro'],
            ['id_city' => 1181, 'id_state' => 5, 'name' => 'Recife'],
            ['id_city' => 1182, 'id_state' => 5, 'name' => 'Remanso'],
            ['id_city' => 1183, 'id_state' => 5, 'name' => 'Remédios'],
            ['id_city' => 1184, 'id_state' => 5, 'name' => 'Retirolândia'],
            ['id_city' => 1185, 'id_state' => 5, 'name' => 'Riachão das Neves'],
            ['id_city' => 1186, 'id_state' => 5, 'name' => 'Riachão do Jacuípe'],
            ['id_city' => 1187, 'id_state' => 5, 'name' => 'Riachão do Utinga'],
            ['id_city' => 1188, 'id_state' => 5, 'name' => 'Riacho da Guia'],
            ['id_city' => 1189, 'id_state' => 5, 'name' => 'Riacho de Santana'],
            ['id_city' => 1190, 'id_state' => 5, 'name' => 'Riacho Seco'],
            ['id_city' => 1191, 'id_state' => 5, 'name' => 'Ribeira do Amparo'],
            ['id_city' => 1192, 'id_state' => 5, 'name' => 'Ribeira do Pombal'],
            ['id_city' => 1193, 'id_state' => 5, 'name' => 'Ribeirão do Largo'],
            ['id_city' => 1194, 'id_state' => 5, 'name' => 'Ribeirão do Salto'],
            ['id_city' => 1195, 'id_state' => 5, 'name' => 'Rio da Dona'],
            ['id_city' => 1196, 'id_state' => 5, 'name' => 'Rio de Contas'],
            ['id_city' => 1197, 'id_state' => 5, 'name' => 'Rio do Antônio'],
            ['id_city' => 1198, 'id_state' => 5, 'name' => 'Rio do Braço'],
            ['id_city' => 1199, 'id_state' => 5, 'name' => 'Rio do Meio'],
            ['id_city' => 1200, 'id_state' => 5, 'name' => 'Rio do Pires'],
            ['id_city' => 1201, 'id_state' => 5, 'name' => 'Rio Fundo'],
            ['id_city' => 1202, 'id_state' => 5, 'name' => 'Rio Real'],
            ['id_city' => 1203, 'id_state' => 5, 'name' => 'Rodelas'],
            ['id_city' => 1204, 'id_state' => 5, 'name' => 'Ruy Barbosa'],
            ['id_city' => 1205, 'id_state' => 5, 'name' => 'Saldanha'],
            ['id_city' => 1206, 'id_state' => 5, 'name' => 'Salgadália'],
            ['id_city' => 1207, 'id_state' => 5, 'name' => 'Salinas da Margarida'],
            ['id_city' => 1208, 'id_state' => 5, 'name' => 'Salobro'],
            ['id_city' => 1209, 'id_state' => 5, 'name' => 'Salvador'],
            ['id_city' => 1210, 'id_state' => 5, 'name' => 'Sambaíba'],
            ['id_city' => 1211, 'id_state' => 5, 'name' => 'Santa Bárbara'],
            ['id_city' => 1212, 'id_state' => 5, 'name' => 'Santa Brígida'],
            ['id_city' => 1213, 'id_state' => 5, 'name' => 'Santa Cruz Cabrália'],
            ['id_city' => 1214, 'id_state' => 5, 'name' => 'Santa Cruz da Vitória'],
            ['id_city' => 1215, 'id_state' => 5, 'name' => 'Santa Inês'],
            ['id_city' => 1216, 'id_state' => 5, 'name' => 'Santa Luzia'],
            ['id_city' => 1217, 'id_state' => 5, 'name' => 'Santa Maria da Vitória'],
            ['id_city' => 1218, 'id_state' => 5, 'name' => 'Santa Rita de Cássia'],
            ['id_city' => 1219, 'id_state' => 5, 'name' => 'Santa Terezinha'],
            ['id_city' => 1220, 'id_state' => 5, 'name' => 'Santaluz'],
            ['id_city' => 1221, 'id_state' => 5, 'name' => 'Santana'],
            ['id_city' => 1222, 'id_state' => 5, 'name' => 'Santana do Sobrado'],
            ['id_city' => 1223, 'id_state' => 5, 'name' => 'Santanópolis'],
            ['id_city' => 1224, 'id_state' => 5, 'name' => 'Santiago do Iguapé'],
            ['id_city' => 1225, 'id_state' => 5, 'name' => 'Santo Amaro'],
            ['id_city' => 1226, 'id_state' => 5, 'name' => 'Santo Antônio de Barcelona'],
            ['id_city' => 1227, 'id_state' => 5, 'name' => 'Santo Antônio de Jesus'],
            ['id_city' => 1228, 'id_state' => 5, 'name' => 'Santo Estevão'],
            ['id_city' => 1229, 'id_state' => 5, 'name' => 'Santo Inácio'],
            ['id_city' => 1230, 'id_state' => 5, 'name' => 'São Desidério'],
            ['id_city' => 1231, 'id_state' => 5, 'name' => 'São Domingos'],
            ['id_city' => 1232, 'id_state' => 5, 'name' => 'São Felipe'],
            ['id_city' => 1233, 'id_state' => 5, 'name' => 'São Félix'],
            ['id_city' => 1234, 'id_state' => 5, 'name' => 'São Félix do Coribe'],
            ['id_city' => 1235, 'id_state' => 5, 'name' => 'São Francisco do Conde'],
            ['id_city' => 1236, 'id_state' => 5, 'name' => 'São Gabriel'],
            ['id_city' => 1237, 'id_state' => 5, 'name' => 'São Gonçalo dos Campos'],
            ['id_city' => 1238, 'id_state' => 5, 'name' => 'São João da Fortaleza'],
            ['id_city' => 1239, 'id_state' => 5, 'name' => 'São João da Vitória'],
            ['id_city' => 1240, 'id_state' => 5, 'name' => 'São José da Vitória'],
            ['id_city' => 1241, 'id_state' => 5, 'name' => 'São José do Colônia'],
            ['id_city' => 1242, 'id_state' => 5, 'name' => 'São José do Jacuípe'],
            ['id_city' => 1243, 'id_state' => 5, 'name' => 'São José do Prado'],
            ['id_city' => 1244, 'id_state' => 5, 'name' => 'São José do Rio Grande'],
            ['id_city' => 1245, 'id_state' => 5, 'name' => 'São Miguel das Matas'],
            ['id_city' => 1246, 'id_state' => 5, 'name' => 'São Paulinho'],
            ['id_city' => 1247, 'id_state' => 5, 'name' => 'São Roque do Paraguaçu'],
            ['id_city' => 1248, 'id_state' => 5, 'name' => 'São Sebastião do Passe'],
            ['id_city' => 1249, 'id_state' => 5, 'name' => 'São Timóteo'],
            ['id_city' => 1250, 'id_state' => 5, 'name' => 'Sapeaçu'],
            ['id_city' => 1251, 'id_state' => 5, 'name' => 'Sátiro Dias'],
            ['id_city' => 1252, 'id_state' => 5, 'name' => 'Saubara'],
            ['id_city' => 1253, 'id_state' => 5, 'name' => 'Saudável'],
            ['id_city' => 1254, 'id_state' => 5, 'name' => 'Saúde'],
            ['id_city' => 1255, 'id_state' => 5, 'name' => 'Seabra'],
            ['id_city' => 1256, 'id_state' => 5, 'name' => 'Sebastião Laranjeiras'],
            ['id_city' => 1257, 'id_state' => 5, 'name' => 'Senhor do Bonfim'],
            ['id_city' => 1258, 'id_state' => 5, 'name' => 'Sento Sé'],
            ['id_city' => 1259, 'id_state' => 5, 'name' => 'Sergi'],
            ['id_city' => 1260, 'id_state' => 5, 'name' => 'Serra da Canabrava'],
            ['id_city' => 1261, 'id_state' => 5, 'name' => 'Serra do Ramalho'],
            ['id_city' => 1262, 'id_state' => 5, 'name' => 'Serra Dourada'],
            ['id_city' => 1263, 'id_state' => 5, 'name' => 'Serra Grande'],
            ['id_city' => 1264, 'id_state' => 5, 'name' => 'Serra Preta'],
            ['id_city' => 1265, 'id_state' => 5, 'name' => 'Serrinha'],
            ['id_city' => 1266, 'id_state' => 5, 'name' => 'Serrolândia'],
            ['id_city' => 1267, 'id_state' => 5, 'name' => 'Simões Filho'],
            ['id_city' => 1268, 'id_state' => 5, 'name' => 'Sítio da Baraúna'],
            ['id_city' => 1269, 'id_state' => 5, 'name' => 'Sítio do Mato'],
            ['id_city' => 1270, 'id_state' => 5, 'name' => 'Sítio do Meio'],
            ['id_city' => 1271, 'id_state' => 5, 'name' => 'Sítio do Quinto'],
            ['id_city' => 1272, 'id_state' => 5, 'name' => 'Sítio Grande'],
            ['id_city' => 1273, 'id_state' => 5, 'name' => 'Sítio Novo'],
            ['id_city' => 1274, 'id_state' => 5, 'name' => 'Soares'],
            ['id_city' => 1275, 'id_state' => 5, 'name' => 'Sobradinho'],
            ['id_city' => 1276, 'id_state' => 5, 'name' => 'Souto Soares'],
            ['id_city' => 1277, 'id_state' => 5, 'name' => 'Subaúma'],
            ['id_city' => 1278, 'id_state' => 5, 'name' => 'Sussuarana'],
            ['id_city' => 1279, 'id_state' => 5, 'name' => 'Tabocas do Brejo Velho'],
            ['id_city' => 1280, 'id_state' => 5, 'name' => 'Taboleiro do Castro'],
            ['id_city' => 1281, 'id_state' => 5, 'name' => 'Taboquinhas'],
            ['id_city' => 1282, 'id_state' => 5, 'name' => 'Taguá'],
            ['id_city' => 1283, 'id_state' => 5, 'name' => 'Tamburil'],
            ['id_city' => 1284, 'id_state' => 5, 'name' => 'Tanhaçu'],
            ['id_city' => 1285, 'id_state' => 5, 'name' => 'Tanque Novo'],
            ['id_city' => 1286, 'id_state' => 5, 'name' => 'Tanquinho'],
            ['id_city' => 1287, 'id_state' => 5, 'name' => 'Tanquinho do Poço'],
            ['id_city' => 1288, 'id_state' => 5, 'name' => 'Taperoá'],
            ['id_city' => 1289, 'id_state' => 5, 'name' => 'Tapiraípe'],
            ['id_city' => 1290, 'id_state' => 5, 'name' => 'Tapirama'],
            ['id_city' => 1291, 'id_state' => 5, 'name' => 'Tapiramutá'],
            ['id_city' => 1292, 'id_state' => 5, 'name' => 'Tapiranga'],
            ['id_city' => 1293, 'id_state' => 5, 'name' => 'Tapúia'],
            ['id_city' => 1294, 'id_state' => 5, 'name' => 'Taquarendi'],
            ['id_city' => 1295, 'id_state' => 5, 'name' => 'Taquarinha'],
            ['id_city' => 1296, 'id_state' => 5, 'name' => 'Tartaruga'],
            ['id_city' => 1297, 'id_state' => 5, 'name' => 'Tauapé'],
            ['id_city' => 1298, 'id_state' => 5, 'name' => 'Teixeira de Freitas'],
            ['id_city' => 1299, 'id_state' => 5, 'name' => 'Teodoro Sampaio'],
            ['id_city' => 1300, 'id_state' => 5, 'name' => 'Teofilândia'],
            ['id_city' => 1301, 'id_state' => 5, 'name' => 'Teolândia'],
            ['id_city' => 1302, 'id_state' => 5, 'name' => 'Terra Nova'],
            ['id_city' => 1303, 'id_state' => 5, 'name' => 'Tijuaçú'],
            ['id_city' => 1304, 'id_state' => 5, 'name' => 'Tiquaruçu'],
            ['id_city' => 1305, 'id_state' => 5, 'name' => 'Tremedal'],
            ['id_city' => 1306, 'id_state' => 5, 'name' => 'Triunfo do Sincorá'],
            ['id_city' => 1307, 'id_state' => 5, 'name' => 'Tucano'],
            ['id_city' => 1308, 'id_state' => 5, 'name' => 'Uauá'],
            ['id_city' => 1309, 'id_state' => 5, 'name' => 'Ubaíra'],
            ['id_city' => 1310, 'id_state' => 5, 'name' => 'Ubaitaba'],
            ['id_city' => 1311, 'id_state' => 5, 'name' => 'Ubatã'],
            ['id_city' => 1312, 'id_state' => 5, 'name' => 'Ubiracaba'],
            ['id_city' => 1313, 'id_state' => 5, 'name' => 'Ubiraitá'],
            ['id_city' => 1314, 'id_state' => 5, 'name' => 'Uibaí'],
            ['id_city' => 1315, 'id_state' => 5, 'name' => 'Umburanas'],
            ['id_city' => 1316, 'id_state' => 5, 'name' => 'Umbuzeiro'],
            ['id_city' => 1317, 'id_state' => 5, 'name' => 'Una'],
            ['id_city' => 1318, 'id_state' => 5, 'name' => 'Urandi'],
            ['id_city' => 1319, 'id_state' => 5, 'name' => 'Uruçuca'],
            ['id_city' => 1320, 'id_state' => 5, 'name' => 'Utinga'],
            ['id_city' => 1321, 'id_state' => 5, 'name' => 'Vale Verde'],
            ['id_city' => 1322, 'id_state' => 5, 'name' => 'Valença'],
            ['id_city' => 1323, 'id_state' => 5, 'name' => 'Valente'],
            ['id_city' => 1324, 'id_state' => 5, 'name' => 'Várzea da Roça'],
            ['id_city' => 1325, 'id_state' => 5, 'name' => 'Várzea do Caldas'],
            ['id_city' => 1326, 'id_state' => 5, 'name' => 'Várzea do Cerco'],
            ['id_city' => 1327, 'id_state' => 5, 'name' => 'Várzea do Poço'],
            ['id_city' => 1328, 'id_state' => 5, 'name' => 'Várzea Nova'],
            ['id_city' => 1329, 'id_state' => 5, 'name' => 'Várzeas'],
            ['id_city' => 1330, 'id_state' => 5, 'name' => 'Varzedo'],
            ['id_city' => 1331, 'id_state' => 5, 'name' => 'Velha Boipeba'],
            ['id_city' => 1332, 'id_state' => 5, 'name' => 'Ventura'],
            ['id_city' => 1333, 'id_state' => 5, 'name' => 'Vera Cruz'],
            ['id_city' => 1334, 'id_state' => 5, 'name' => 'Vereda'],
            ['id_city' => 1335, 'id_state' => 5, 'name' => 'Vila do Café'],
            ['id_city' => 1336, 'id_state' => 5, 'name' => 'Vitória da Conquista'],
            ['id_city' => 1337, 'id_state' => 5, 'name' => 'Volta Grande'],
            ['id_city' => 1338, 'id_state' => 5, 'name' => 'Wagner'],
            ['id_city' => 1339, 'id_state' => 5, 'name' => 'Wanderley'],
            ['id_city' => 1340, 'id_state' => 5, 'name' => 'Wenceslau Guimarães'],
            ['id_city' => 1341, 'id_state' => 5, 'name' => 'Xique-Xique'],
            ['id_city' => 1342, 'id_state' => 6, 'name' => 'Abaiara'],
            ['id_city' => 1343, 'id_state' => 6, 'name' => 'Abílio Martins'],
            ['id_city' => 1344, 'id_state' => 6, 'name' => 'Acarape'],
            ['id_city' => 1345, 'id_state' => 6, 'name' => 'Acaraú'],
            ['id_city' => 1346, 'id_state' => 6, 'name' => 'Acopiara'],
            ['id_city' => 1347, 'id_state' => 6, 'name' => 'Adrianópolis'],
            ['id_city' => 1348, 'id_state' => 6, 'name' => 'Água Verde'],
            ['id_city' => 1349, 'id_state' => 6, 'name' => 'Aguaí'],
            ['id_city' => 1350, 'id_state' => 6, 'name' => 'Aiuá'],
            ['id_city' => 1351, 'id_state' => 6, 'name' => 'Aiuaba'],
            ['id_city' => 1352, 'id_state' => 6, 'name' => 'Alagoinha'],
            ['id_city' => 1353, 'id_state' => 6, 'name' => 'Alcântaras'],
            ['id_city' => 1354, 'id_state' => 6, 'name' => 'Algodões'],
            ['id_city' => 1355, 'id_state' => 6, 'name' => 'Almofala'],
            ['id_city' => 1356, 'id_state' => 6, 'name' => 'Altaneira'],
            ['id_city' => 1357, 'id_state' => 6, 'name' => 'Alto Santo'],
            ['id_city' => 1358, 'id_state' => 6, 'name' => 'Amanaiara'],
            ['id_city' => 1359, 'id_state' => 6, 'name' => 'Amanari'],
            ['id_city' => 1360, 'id_state' => 6, 'name' => 'Amaniutuba'],
            ['id_city' => 1361, 'id_state' => 6, 'name' => 'Amarelas'],
            ['id_city' => 1362, 'id_state' => 6, 'name' => 'Amaro'],
            ['id_city' => 1363, 'id_state' => 6, 'name' => 'América'],
            ['id_city' => 1364, 'id_state' => 6, 'name' => 'Amontada'],
            ['id_city' => 1365, 'id_state' => 6, 'name' => 'Anauá'],
            ['id_city' => 1366, 'id_state' => 6, 'name' => 'Aningás'],
            ['id_city' => 1367, 'id_state' => 6, 'name' => 'Anjinhos'],
            ['id_city' => 1368, 'id_state' => 6, 'name' => 'Antonina do Norte'],
            ['id_city' => 1369, 'id_state' => 6, 'name' => 'Antônio Bezerra'],
            ['id_city' => 1370, 'id_state' => 6, 'name' => 'Antônio Diogo'],
            ['id_city' => 1371, 'id_state' => 6, 'name' => 'Antônio Marques'],
            ['id_city' => 1372, 'id_state' => 6, 'name' => 'Aprazível'],
            ['id_city' => 1373, 'id_state' => 6, 'name' => 'Apuiarés'],
            ['id_city' => 1374, 'id_state' => 6, 'name' => 'Aquinópolis'],
            ['id_city' => 1375, 'id_state' => 6, 'name' => 'Aquiraz'],
            ['id_city' => 1376, 'id_state' => 6, 'name' => 'Araçás'],
            ['id_city' => 1377, 'id_state' => 6, 'name' => 'Aracati'],
            ['id_city' => 1378, 'id_state' => 6, 'name' => 'Aracatiaçu'],
            ['id_city' => 1379, 'id_state' => 6, 'name' => 'Aracatiara'],
            ['id_city' => 1380, 'id_state' => 6, 'name' => 'Aracoiaba'],
            ['id_city' => 1381, 'id_state' => 6, 'name' => 'Arajara'],
            ['id_city' => 1382, 'id_state' => 6, 'name' => 'Aranaú'],
            ['id_city' => 1383, 'id_state' => 6, 'name' => 'Arapá'],
            ['id_city' => 1384, 'id_state' => 6, 'name' => 'Arapari'],
            ['id_city' => 1385, 'id_state' => 6, 'name' => 'Araporanga'],
            ['id_city' => 1386, 'id_state' => 6, 'name' => 'Araquém'],
            ['id_city' => 1387, 'id_state' => 6, 'name' => 'Ararendá'],
            ['id_city' => 1388, 'id_state' => 6, 'name' => 'Araripe'],
            ['id_city' => 1389, 'id_state' => 6, 'name' => 'Arariús'],
            ['id_city' => 1390, 'id_state' => 6, 'name' => 'Aratama'],
            ['id_city' => 1391, 'id_state' => 6, 'name' => 'Araticum'],
            ['id_city' => 1392, 'id_state' => 6, 'name' => 'Aratuba'],
            ['id_city' => 1393, 'id_state' => 6, 'name' => 'Areial'],
            ['id_city' => 1394, 'id_state' => 6, 'name' => 'Ariscos dos Marianos'],
            ['id_city' => 1395, 'id_state' => 6, 'name' => 'Arneiroz'],
            ['id_city' => 1396, 'id_state' => 6, 'name' => 'Aroeiras'],
            ['id_city' => 1397, 'id_state' => 6, 'name' => 'Arrojado'],
            ['id_city' => 1398, 'id_state' => 6, 'name' => 'Aruaru'],
            ['id_city' => 1399, 'id_state' => 6, 'name' => 'Assaré'],
            ['id_city' => 1400, 'id_state' => 6, 'name' => 'Assunção'],
            ['id_city' => 1401, 'id_state' => 6, 'name' => 'Aurora'],
            ['id_city' => 1402, 'id_state' => 6, 'name' => 'Baixa Grande'],
            ['id_city' => 1403, 'id_state' => 6, 'name' => 'Baixio'],
            ['id_city' => 1404, 'id_state' => 6, 'name' => 'Baixio da Donana'],
            ['id_city' => 1405, 'id_state' => 6, 'name' => 'Banabuiú'],
            ['id_city' => 1406, 'id_state' => 6, 'name' => 'Bandeira'],
            ['id_city' => 1407, 'id_state' => 6, 'name' => 'Barão de Aquiraz'],
            ['id_city' => 1408, 'id_state' => 6, 'name' => 'Barbalha'],
            ['id_city' => 1409, 'id_state' => 6, 'name' => 'Barra'],
            ['id_city' => 1410, 'id_state' => 6, 'name' => 'Barra'],
            ['id_city' => 1411, 'id_state' => 6, 'name' => 'Barra'],
            ['id_city' => 1412, 'id_state' => 6, 'name' => 'Barra do Sotero'],
            ['id_city' => 1413, 'id_state' => 6, 'name' => 'Barra Nova'],
            ['id_city' => 1414, 'id_state' => 6, 'name' => 'Barreira'],
            ['id_city' => 1415, 'id_state' => 6, 'name' => 'Barreira dos Vianas'],
            ['id_city' => 1416, 'id_state' => 6, 'name' => 'Barreiras'],
            ['id_city' => 1417, 'id_state' => 6, 'name' => 'Barreiros'],
            ['id_city' => 1418, 'id_state' => 6, 'name' => 'Barreiros'],
            ['id_city' => 1419, 'id_state' => 6, 'name' => 'Barreiros'],
            ['id_city' => 1420, 'id_state' => 6, 'name' => 'Barrento'],
            ['id_city' => 1421, 'id_state' => 6, 'name' => 'Barro'],
            ['id_city' => 1422, 'id_state' => 6, 'name' => 'Barro Alto'],
            ['id_city' => 1423, 'id_state' => 6, 'name' => 'Barroquinha'],
            ['id_city' => 1424, 'id_state' => 6, 'name' => 'Baturité'],
            ['id_city' => 1425, 'id_state' => 6, 'name' => 'Baú'],
            ['id_city' => 1426, 'id_state' => 6, 'name' => 'Beberibe'],
            ['id_city' => 1427, 'id_state' => 6, 'name' => 'Bela Cruz'],
            ['id_city' => 1428, 'id_state' => 6, 'name' => 'Bela Vista'],
            ['id_city' => 1429, 'id_state' => 6, 'name' => 'Betânia'],
            ['id_city' => 1430, 'id_state' => 6, 'name' => 'Bitupitá'],
            ['id_city' => 1431, 'id_state' => 6, 'name' => 'Bixopa'],
            ['id_city' => 1432, 'id_state' => 6, 'name' => 'Boa Água'],
            ['id_city' => 1433, 'id_state' => 6, 'name' => 'Boa Esperança'],
            ['id_city' => 1434, 'id_state' => 6, 'name' => 'Boa Viagem'],
            ['id_city' => 1435, 'id_state' => 6, 'name' => 'Boa Vista'],
            ['id_city' => 1436, 'id_state' => 6, 'name' => 'Boa Vista do Caxitoré'],
            ['id_city' => 1437, 'id_state' => 6, 'name' => 'Bonfim'],
            ['id_city' => 1438, 'id_state' => 6, 'name' => 'Bonhu'],
            ['id_city' => 1439, 'id_state' => 6, 'name' => 'Bonito'],
            ['id_city' => 1440, 'id_state' => 6, 'name' => 'Borges'],
            ['id_city' => 1441, 'id_state' => 6, 'name' => 'Brejinho'],
            ['id_city' => 1442, 'id_state' => 6, 'name' => 'Brejo Grande'],
            ['id_city' => 1443, 'id_state' => 6, 'name' => 'Brejo Santo'],
            ['id_city' => 1444, 'id_state' => 6, 'name' => 'Brotas'],
            ['id_city' => 1445, 'id_state' => 6, 'name' => 'Buritizal'],
            ['id_city' => 1446, 'id_state' => 6, 'name' => 'Buritizinho'],
            ['id_city' => 1447, 'id_state' => 6, 'name' => 'Cabreiro'],
            ['id_city' => 1448, 'id_state' => 6, 'name' => 'Cachoeira'],
            ['id_city' => 1449, 'id_state' => 6, 'name' => 'Cachoeira Grande'],
            ['id_city' => 1450, 'id_state' => 6, 'name' => 'Caiçara'],
            ['id_city' => 1451, 'id_state' => 6, 'name' => 'Caiçarinha'],
            ['id_city' => 1452, 'id_state' => 6, 'name' => 'Caio Prado'],
            ['id_city' => 1453, 'id_state' => 6, 'name' => 'Caioca'],
            ['id_city' => 1454, 'id_state' => 6, 'name' => 'Caipu'],
            ['id_city' => 1455, 'id_state' => 6, 'name' => 'Calabaça'],
            ['id_city' => 1456, 'id_state' => 6, 'name' => 'Caldeirão'],
            ['id_city' => 1457, 'id_state' => 6, 'name' => 'Califórnia'],
            ['id_city' => 1458, 'id_state' => 6, 'name' => 'Camará'],
            ['id_city' => 1459, 'id_state' => 6, 'name' => 'Camboas'],
            ['id_city' => 1460, 'id_state' => 6, 'name' => 'Camilos'],
            ['id_city' => 1461, 'id_state' => 6, 'name' => 'Camocim'],
            ['id_city' => 1462, 'id_state' => 6, 'name' => 'Campanário'],
            ['id_city' => 1463, 'id_state' => 6, 'name' => 'Campestre'],
            ['id_city' => 1464, 'id_state' => 6, 'name' => 'Campos Sales'],
            ['id_city' => 1465, 'id_state' => 6, 'name' => 'Canaan'],
            ['id_city' => 1466, 'id_state' => 6, 'name' => 'Canafistula'],
            ['id_city' => 1467, 'id_state' => 6, 'name' => 'Cangati'],
            ['id_city' => 1468, 'id_state' => 6, 'name' => 'Canindé'],
            ['id_city' => 1469, 'id_state' => 6, 'name' => 'Canindezinho'],
            ['id_city' => 1470, 'id_state' => 6, 'name' => 'Capistrano'],
            ['id_city' => 1471, 'id_state' => 6, 'name' => 'Caponga'],
            ['id_city' => 1472, 'id_state' => 6, 'name' => 'Caponga da Bernarda'],
            ['id_city' => 1473, 'id_state' => 6, 'name' => 'Caracará'],
            ['id_city' => 1474, 'id_state' => 6, 'name' => 'Caridade'],
            ['id_city' => 1475, 'id_state' => 6, 'name' => 'Cariré'],
            ['id_city' => 1476, 'id_state' => 6, 'name' => 'Caririaçu'],
            ['id_city' => 1477, 'id_state' => 6, 'name' => 'Cariús'],
            ['id_city' => 1478, 'id_state' => 6, 'name' => 'Cariutaba'],
            ['id_city' => 1479, 'id_state' => 6, 'name' => 'Carmelópolis'],
            ['id_city' => 1480, 'id_state' => 6, 'name' => 'Carnaubal'],
            ['id_city' => 1481, 'id_state' => 6, 'name' => 'Carnaúbas'],
            ['id_city' => 1482, 'id_state' => 6, 'name' => 'Carnaubinha'],
            ['id_city' => 1483, 'id_state' => 6, 'name' => 'Carquejo'],
            ['id_city' => 1484, 'id_state' => 6, 'name' => 'Carrapateiras'],
            ['id_city' => 1485, 'id_state' => 6, 'name' => 'Caruataí'],
            ['id_city' => 1486, 'id_state' => 6, 'name' => 'Carvalho'],
            ['id_city' => 1487, 'id_state' => 6, 'name' => 'Carvoeiro'],
            ['id_city' => 1488, 'id_state' => 6, 'name' => 'Cascavel'],
            ['id_city' => 1489, 'id_state' => 6, 'name' => 'Castanhão'],
            ['id_city' => 1490, 'id_state' => 6, 'name' => 'Catarina'],
            ['id_city' => 1491, 'id_state' => 6, 'name' => 'Catolé'],
            ['id_city' => 1492, 'id_state' => 6, 'name' => 'Catuana'],
            ['id_city' => 1493, 'id_state' => 6, 'name' => 'Catunda'],
            ['id_city' => 1494, 'id_state' => 6, 'name' => 'Caucaia'],
            ['id_city' => 1495, 'id_state' => 6, 'name' => 'Caxitoré'],
            ['id_city' => 1496, 'id_state' => 6, 'name' => 'Caxitoré'],
            ['id_city' => 1497, 'id_state' => 6, 'name' => 'Cedro'],
            ['id_city' => 1498, 'id_state' => 6, 'name' => 'Cemoaba'],
            ['id_city' => 1499, 'id_state' => 6, 'name' => 'Chaval'],
            ['id_city' => 1500, 'id_state' => 6, 'name' => 'Choró'],
            ['id_city' => 1501, 'id_state' => 6, 'name' => 'Chorozinho'],
            ['id_city' => 1502, 'id_state' => 6, 'name' => 'Cipó dos Anjos'],
            ['id_city' => 1503, 'id_state' => 6, 'name' => 'Cococi'],
            ['id_city' => 1504, 'id_state' => 6, 'name' => 'Codiá'],
            ['id_city' => 1505, 'id_state' => 6, 'name' => 'Coité'],
            ['id_city' => 1506, 'id_state' => 6, 'name' => 'Colina'],
            ['id_city' => 1507, 'id_state' => 6, 'name' => 'Conceição'],
            ['id_city' => 1508, 'id_state' => 6, 'name' => 'Coreaú'],
            ['id_city' => 1509, 'id_state' => 6, 'name' => 'Córrego dos Fernandes'],
            ['id_city' => 1510, 'id_state' => 6, 'name' => 'Crateús'],
            ['id_city' => 1511, 'id_state' => 6, 'name' => 'Crato'],
            ['id_city' => 1512, 'id_state' => 6, 'name' => 'Crioulos'],
            ['id_city' => 1513, 'id_state' => 6, 'name' => 'Cristais'],
            ['id_city' => 1514, 'id_state' => 6, 'name' => 'Croatá'],
            ['id_city' => 1515, 'id_state' => 6, 'name' => 'Cruxati'],
            ['id_city' => 1516, 'id_state' => 6, 'name' => 'Cruz'],
            ['id_city' => 1517, 'id_state' => 6, 'name' => 'Cruz de Pedra'],
            ['id_city' => 1518, 'id_state' => 6, 'name' => 'Cruzeirinho'],
            ['id_city' => 1519, 'id_state' => 6, 'name' => 'Cuncas'],
            ['id_city' => 1520, 'id_state' => 6, 'name' => 'Curatis'],
            ['id_city' => 1521, 'id_state' => 6, 'name' => 'Curupira'],
            ['id_city' => 1522, 'id_state' => 6, 'name' => 'Custódio'],
            ['id_city' => 1523, 'id_state' => 6, 'name' => 'Daniel de Queirós'],
            ['id_city' => 1524, 'id_state' => 6, 'name' => 'Delmiro Gouveia'],
            ['id_city' => 1525, 'id_state' => 6, 'name' => 'Deputado Irapuan Pinheiro'],
            ['id_city' => 1526, 'id_state' => 6, 'name' => 'Deserto'],
            ['id_city' => 1527, 'id_state' => 6, 'name' => 'Dom Leme'],
            ['id_city' => 1528, 'id_state' => 6, 'name' => 'Dom Maurício'],
            ['id_city' => 1529, 'id_state' => 6, 'name' => 'Dom Quintino'],
            ['id_city' => 1530, 'id_state' => 6, 'name' => 'Domingos da Costa'],
            ['id_city' => 1531, 'id_state' => 6, 'name' => 'Donato'],
            ['id_city' => 1532, 'id_state' => 6, 'name' => 'Dourado'],
            ['id_city' => 1533, 'id_state' => 6, 'name' => 'Ebron'],
            ['id_city' => 1534, 'id_state' => 6, 'name' => 'Ema'],
            ['id_city' => 1535, 'id_state' => 6, 'name' => 'Ematuba'],
            ['id_city' => 1536, 'id_state' => 6, 'name' => 'Encantado'],
            ['id_city' => 1537, 'id_state' => 6, 'name' => 'Engenheiro João Tomé'],
            ['id_city' => 1538, 'id_state' => 6, 'name' => 'Engenheiro José Lopes'],
            ['id_city' => 1539, 'id_state' => 6, 'name' => 'Engenho Velho'],
            ['id_city' => 1540, 'id_state' => 6, 'name' => 'Ererê'],
            ['id_city' => 1541, 'id_state' => 6, 'name' => 'Espacinha'],
            ['id_city' => 1542, 'id_state' => 6, 'name' => 'Esperança'],
            ['id_city' => 1543, 'id_state' => 6, 'name' => 'Várzea dos Espinhos'],
            ['id_city' => 1544, 'id_state' => 6, 'name' => 'Eusébio'],
            ['id_city' => 1545, 'id_state' => 6, 'name' => 'Farias Brito'],
            ['id_city' => 1546, 'id_state' => 6, 'name' => 'Fátima'],
            ['id_city' => 1547, 'id_state' => 6, 'name' => 'Feiticeiro'],
            ['id_city' => 1548, 'id_state' => 6, 'name' => 'Feitosa'],
            ['id_city' => 1549, 'id_state' => 6, 'name' => 'Felizardo'],
            ['id_city' => 1550, 'id_state' => 6, 'name' => 'Flamengo'],
            ['id_city' => 1551, 'id_state' => 6, 'name' => 'Flores'],
            ['id_city' => 1552, 'id_state' => 6, 'name' => 'Forquilha'],
            ['id_city' => 1553, 'id_state' => 6, 'name' => 'Fortaleza'],
            ['id_city' => 1554, 'id_state' => 6, 'name' => 'Fortim'],
            ['id_city' => 1555, 'id_state' => 6, 'name' => 'Frecheirinha'],
            ['id_city' => 1556, 'id_state' => 6, 'name' => 'Gado'],
            ['id_city' => 1557, 'id_state' => 6, 'name' => 'Gado dos Rodrigues'],
            ['id_city' => 1558, 'id_state' => 6, 'name' => 'Gameleira de São Sebastião'],
            ['id_city' => 1559, 'id_state' => 6, 'name' => 'Garças'],
            ['id_city' => 1560, 'id_state' => 6, 'name' => 'Gázea'],
            ['id_city' => 1561, 'id_state' => 6, 'name' => 'General Sampaio'],
            ['id_city' => 1562, 'id_state' => 6, 'name' => 'General Tibúrcio'],
            ['id_city' => 1563, 'id_state' => 6, 'name' => 'Jenipapeiro'],
            ['id_city' => 1564, 'id_state' => 6, 'name' => 'Gereraú'],
            ['id_city' => 1565, 'id_state' => 6, 'name' => 'Giqui'],
            ['id_city' => 1566, 'id_state' => 6, 'name' => 'Girau'],
            ['id_city' => 1567, 'id_state' => 6, 'name' => 'Graça'],
            ['id_city' => 1568, 'id_state' => 6, 'name' => 'Granja'],
            ['id_city' => 1569, 'id_state' => 6, 'name' => 'Granjeiro'],
            ['id_city' => 1570, 'id_state' => 6, 'name' => 'Groairas'],
            ['id_city' => 1571, 'id_state' => 6, 'name' => 'Guaiúba'],
            ['id_city' => 1572, 'id_state' => 6, 'name' => 'Guajiru'],
            ['id_city' => 1573, 'id_state' => 6, 'name' => 'Guanacés']
        ]);
    }
}
